setting up test framework
atlp-rwanda/orcas-phantom-backend pull request #3
Opened 2020-09-24 08:45 UTC by fistonhn

#### What does this PR do?
Implementing test
#### Description of Task to be completed?
-installing Jest and its needed dependencies
-setting up Jest in the project
#### How should this be manually tested?
clone Repo and then run npm test
#### Any background context you want to provide?
all API should be tested
#### What are the relevant pivotal tracker stories?
https://trello.com/c/vepfL3tE/21-setup-testing-environment
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2020-09-24 10:28 UTC, Isaackomeza requested changes
Thank you @fistonhn , your test is passing well but consider resolving eslint errors within the main.test.js file
![err](https://user-images.githubusercontent.com/66563235/94133752-5a63e380-fe61-11ea-9d51-df1c04d9155f.PNG)

2020-09-25 07:55 UTC, Rwandarushya approved these changes

2020-09-25 08:00 UTC, Malaba6 approved these changes

2020-09-25 08:01 UTC, merged

2020-09-25 09:02 UTC, Isaackomeza approved these changes